# datasource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comprehensive
    username: ohgiraffers
    password: ohgiraffers

# jpq config
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# file upload size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# sever port
server:
  port: 8001

# image file
#http://localhost:8001/productimgs/ 서버쪽으로 요청하는 주소
#dir 실제저장할 디렉토리
image:
  image-url: http://localhost:8001/productimgs/
  image-dir: src/main/resources/staic/productimgs